---
- hosts: all
  become: yes
  roles:
          - { role: init, tags: ["init"] }
          - { role: docker, tags: ["docker"] }
          - { role: wordpress, tags: ["wordpress"] }
          - { role: haproxy,when: inventory_hostname_short=="node0" ,tags: ["haproxy"] }
