---

- name: create wordpress container
  docker_container:
    name: wordpress
    image: wordpress
    state: started
    env:
      WORDPRESS_DB_HOST: 192.168.1.3
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "{{ mysql_pass }}" 
    ports:
     - "8080:80"
