---

- name: create wordpress container
  docker_container:
    name: "wordpress{{ item }}"
    image: wordpress
    state: started
    env:
      WORDPRESS_DB_HOST: 192.168.1.3
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "{{ mysql_pass }}"
      WORDPRESS_TABLE_PREFIX: "wp_ha_"
      WORDPRESS_SITE_URL: http://localhost/
    ports:
      - "8{{ item }}80:80"
  with_items:
    - 1
    - 2
    - 3
