---
forwarders:
  - 8.8.8.8
  - 1.1.1.1
  - 9.9.9.10
localnets:
  - 192.168.1.0/24
  - 10.0.2.0/24
  - localhost
NS1: 'infra.                IN      NS      infra01.itinfra.'
NS2: 'infra.                IN      NS      infra02.itinfra.'
AR1: 'infra01.itinfra.        IN      A       192.168.1.2'
AR2: 'infra02.itinfra.        IN      A       192.168.1.3'
AR3: 'ns        IN      A       192.168.1.2'
AR4: 'ns        IN      A       192.168.1.3'
CNAME1: 'ns1.itinfra.    CNAME infra01.itinfra.'
CNAME2: 'ns2.itinfra.    CNAME infra02.itinfra.'

