---
- hosts: all
  become: yes
  tasks:

    - name: systemd-resolved
      service:
        name: systemd-resolved
        state: stopped
        enabled: no

  handlers:
    - name: netplan apply
      shell: netplan apply

- name: setup dns
  hosts: dns
  become: yes
  gather_facts: yes
  tasks:

    - name: ensure that apt can resolve
      lineinfile:
        path: /etc/resolv.conf 
        state: present
        line: '{{ item }}'
      with_items:
        - 'nameserver 192.168.1.2'
        - 'nameserver 192.168.1.3'

    - name: dns package
      apt:
        package: bind9
    
    - name: config bind
      template:
        src: templates/named.conf.options.j2
        dest: /etc/bind/named.conf.options
      notify:
        - restart bind
        - check conf

    - name: config bind.local
      template:
        src: templates/named.conf.local.j2
        dest: /etc/bind/named.conf.local
      notify:
        - restart bind
        - check conf
 
    - name: config db
      template:
        src: templates/db.j2
        dest: /etc/bind/db
      when: dns_role == "master"
      notify:
        - bind reload db
  
    - name: config db ptr
      template:
        src: templates/db.ptr.j2
        dest: /etc/bind/db.ptr
      when: dns_role == "master"
      notify:
        - bind reload db

  handlers:
    - name: modify resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        state: present
        line: "{{ item }}"
      with_items:
        - 'nameserver 192.168.1.2'
        - 'nameserver 192.168.1.3'

    - name: check conf
      shell: named-checkconf
  
    - name: restart bind
      service:
        name: bind9
        state: restarted
  
    - name: bind reload db
      shell: rndc reload 
