---
- group:
    name: node_exporter
    state: present

- name: Create node_exporter user
  user: name=node_exporter shell=/usr/sbin/nologin group=node_exporter system=yes

- name: Check that the file exists
  stat:
    path: /opt/node_exporter-0.18.1.linux-amd64.tar.gz
  register: stat_result

- name: Download
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
    dest: /opt/
  when: stat_result.stat.exists == False

- name: folder
  file:
    path: /opt/node_exporter
    state: directory
    mode: '0755'

- name: untar
  unarchive:
    src: /opt/node_exporter-0.18.1.linux-amd64.tar.gz
    dest: /opt/node_exporter
    remote_src: yes
    extra_opts:
      - --strip-components=1

- name: systemd node_exporter
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: start exporter
  service:
    name: node_exporter
    state: started
    enabled: yes
