---
- hosts: node1 
  become: yes


  tasks:

    - name: create backup user
      user: name=backup shell=/bin/bash group=backup system=yes create_home=True

    - name: create required directories
      file:
        path: /var/backups/.ssh/
        state: directory
        owner: 'backup'
        group: 'backup'
        mode:  '0700'

    - name: deploy ssh keys
      copy:
        src=backup.pub
        dest=/var/backups/.ssh/authorized_keys
        owner=backup
        group=backup
        mode=0600

    - name: deploy ssh keys
      copy:
        src=backup.pub
        dest=/home/backup/.ssh/authorized_keys
        owner=backup
        group=backup
        mode=0600

    - name: create srv/backup directory
      file:
        path: /srv/backup
        state: directory
        recurse: yes
        owner: 'backup'
        group: 'backup'
        mode:  '0700'
