---
- name: modify resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    state: present
    line: "{{ item }}"
  with_items:
    - 'nameserver 192.168.1.2'
    - 'nameserver 192.168.1.3'

- name: check conf
  shell: named-checkconf

- name: restart bind
  service:
    name: bind9
    state: restarted

- name: bind reload db
  shell: rndc reload

