---
- hosts: all
  become: yes
  roles:
    - { role: init }
    - { role: bind }
    - { role: exporters }
    - { role: prometheus, when: inventory_hostname_short=="node0", tags: [prometheus]}
    - { role: grafana, tags: [grafana] }

